version: "3"
services:
   web:
      image: nginx:latest
      volumes:
#         - ./opt/nginx:/etc/nginx
         - ./opt/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
         - ./opt/nginx/log:/var/log/nginx
         - ./opt/www:/usr/share/nginx/html
         - ./opt/bin/ngrok:/usr/local/bin/ngrok
#      deploy:
#         replicas: 1
      restart: unless-stopped
      ports:
         - "80:80"
         - "443:443"
      networks:
         - webnet
networks:
   webnet:
